### ISSUE TITLE
flow-api-translator: add support for TS generation from React.ElementProps

### ISSUE THREAD

**Issue by necolas** [facebook/hermes#1053]
## Bug Description

flow-api-translator doesn't support TS libdef generation if the Flow source types are using `React.ElementProps` (and possibly other React types).

```
Failed to process file: [path]
ExpectedTranslationError: > 18 |     React.ElementProps<'a'>,
     |     ^^^^^^^^^^^^^^^^^^^^^^^ Unsupported feature: Translating "React.ElementProps" is currently not supported.
    at translationError ([path]/node_modules/flow-api-translator/dist/utils/ErrorUtils.js:67:10)
    at translationError ([path]/node_modules/flow-api-translator/dist/flowDefToTSDef.js:64:45)
    at unsupportedTranslationError ([path]/node_modules/flow-api-translator/dist/flowDefToTSDef.js:76:12)
    at GenericTypeAnnotation ([path]/node_modules/flow-api-translator/dist/flowDefToTSDef.js:1602:19)
    at transform.<computed> [as GenericTypeAnnotation] ([path]/node_modules/flow-api-translator/dist/flowDefToTSDef.js:2370:22)
    at TypeAnnotationType ([path]/node_modules/flow-api-translator/dist/flowDefToTSDef.js:2222:28)
    at transform.<computed> ([path]/node_modules/flow-api-translator/dist/flowDefToTSDef.js:2370:22)
    at Array.map (<anonymous>)
    at TypeParameterInstantiation ([path]/node_modules/flow-api-translator/dist/flowDefToTSDef.js:2345:29)
    at transform.<computed> [as TypeParameterInstantiation] ([path]/node_modules/flow-api-translator/dist/flowDefToTSDef.js:2370:22)
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: [workspace]
npm ERR!   at location: [path]
```

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version:
React Native version (if any):
OS version (if any):
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

## Steps To Reproduce

1. Use React.ElementProps<'div'> in a source file
2. Try to generate TS types using `flowDefToTSDef`

## The Expected Behavior

No errors

**Comment by noahlemen** [comment]
https://github.com/facebook/hermes/commit/cc0fd60b30d81bfa2f4b13367301244e9189f1e5 should close this!
