### ISSUE TITLE
Ninja: error: unknown target 'github-cli-release' when packaging CLI binaries

### ISSUE THREAD

**Issue by carlosalmonte04** [facebook/hermes#1069]
## Bug Description

My goal is to make use of a custom build of hermes running in a react native app. Following the docs works fine for me until I have to run the command below.

– The only thing that comes to mind is that I had to add `ANDROID_SDK_ROOT` to my environment, I made it the same as `ANDROID_SDK`. [_Also `ANDROID_SDK_ROOT` is deprecated._](https://developer.android.com/tools/variables#envar)

```
$ ninja github-cli-release
ninja: error: unknown target 'github-cli-release'
```

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.12.0
React Native version (if any): N/A
OS version (if any): N/A
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

## Steps To Reproduce

1. Run the commands below to build a release version of Hermes:
`cmake -S hermes -B build_release -G Ninja -DCMAKE_BUILD_TYPE=Release`
`cmake --build ./build_release`
2. Run the command below to package CLI binaries for the current platform
`cd $HERMES_WS_DIR/build_release && ninja github-cli-release`

Produces error "ninja: error: unknown target 'github-cli-release'" 

code example:
N/A

## The Expected Behavior
Command `ninja github-cli-release` should run successfully.

**Comment by neildhar** [comment]
Thank you for reporting this, those docs are unfortunately out-of-date. Hermes is now built and distributed for Android by React Native itself, so the correct way to consume Hermes from source is to set the `REACT_NATIVE_OVERRIDE_HERMES_DIR` environment variable to point to the custom Hermes source, and then build your RN app.

**Comment by carlosalmonte04** [comment]
Thanks for your response @neildhar. I tried setting the environment variable and it did not work. I pointed to the build I got from running `$ cmake --build ./build_release`, so my environment variable looked like this `REACT_NATIVE_OVERRIDE_HERMES_DIR="<my-hermes-working-directory>/build_release"`.

Please let me know. I'm only trying to add a new `arrayPrototype<myCustomFunction>` and use it on my react native app, Android and iOS.

**Comment by neildhar** [comment]
@carlosalmonte04 You need to point it to your hermes source directory, not a build directory. Note that this only applies to Android, I'm not familiar with the steps for iOS.

Out of curiosity, does your change require access to VM internals? Otherwise such extensions are usually added either in JS or through JSI.

**Comment by carlosalmonte04** [comment]
No luck :/. 
1. I added the environment variable pointing to the source directory (`REACT_NATIVE_OVERRIDE_HERMES_DIR="<my-hermes-working-directory>/hermes"`)
2. Refreshed profile in terminal `source ~/.bash_profile`, also did `echo $REACT_NATIVE_OVERRIDE_HERMES_DIR` just to confirm
3. Cleaned and the built the app using `cd android && ./gradlew clean && cd .. && npx react-native run-android ` 

Answer to your question, my change required changes in:

`lib/VM/JSLib/Array.cpp`
`include/hermes/VM/NativeFunctions.def`
`include/hermes/VM/PredefinedStrings.def`

Are you suggesting that this could be done by adding something like a shim/polyfill* in JS? If so I agree, I wonder how it could be done in JSI though. I just did it this way to dig a little deeper into hermes, maybe I should have tried a different little project.

**Comment by neildhar** [comment]
That's odd, since we use this build process to test Hermes in CI. If the app is on an older version of RN, it is possible that's why Hermes is not being rebuilt. (this was added in https://github.com/facebook/react-native/commit/68fde3b35b9ac10e8d124fc079150d52438ba6c7)

If not, perhaps @cortinico knows why this isn't working.

> that this could be done by adding something like a shim/polyfill* in JS

That's what I was suggesting, but of course we welcome and encourage people digging into Hermes' code.

**Comment by carlosalmonte04** [comment]
Thanks. I tested on a new react native app version 0.72.3 and had the same failing result.

No rush on my end.

**Comment by cortinico** [comment]
Hey @carlosalmonte04 
1. First you'll have to enable a build from source https://reactnative.dev/contributing/how-to-build-from-source
2. Make sure that you're able to actually build from source without errors
3. Then you'll have to set `export REACT_NATIVE_OVERRIDE_HERMES_DIR=/path/to/your/hermes/repo`
4. And then build again, this build will use Hermes from your custom repository this time

**Comment by carlosalmonte04** [comment]
Thanks for the help. I got stuck on step 2. It builds successfully and crashes upon launching with the error below (from `adb logcat`):

```
07-27 20:51:28.361 14288 14339 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
07-27 20:51:28.361 14288 14339 E AndroidRuntime: Process: com.awesomeproject072, PID: 14288
07-27 20:51:28.361 14288 14339 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/drawee/backends/pipeline/info/ImagePerfDataListener;
07-27 20:51:28.361 14288 14339 E AndroidRuntime: 	at com.awesomeproject072.ReactNativeFlipper.initializeFlipper(ReactNativeFlipper.java:33)
07-27 20:51:28.361 14288 14339 E AndroidRuntime: 	at com.awesomeproject072.MainApplication.onCreate(MainApplication.java:60)
07-27 20:51:28.361 14288 14339 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
07-27 20:51:28.361 14288 14339 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
07-27 20:51:28.361 14288 14339 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
07-27 20:51:28.361 14288 14339 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
07-27 20:51:28.361 14288 14339 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-27 20:51:28.361 14288 14339 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-27 20:51:28.361 14288 14339 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-27 20:51:28.361 14288 14339 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
07-27 20:51:28.361 14288 14339 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-27 20:51:28.361 14288 14339 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-27 20:51:28.361 14288 14339 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

I'll continue playing around and see if I find a solution.

**Comment by neildhar** [comment]
Transferring this issue to RN since this is primarily an RN discussion.
