### ISSUE TITLE
`TypeError: Cannot read properties of null (reading 'range')` using hermes-eslint, indent rule, and a FunctionExpression as a Property

### ISSUE THREAD

**Issue by mwiencek** [facebook/hermes#1088]
## Bug Description

eslint 8.46.0
hermes-eslint 0.15.1

.eslintrc.yaml:

```yaml
root: true

parser: "hermes-eslint"

rules:
  indent: error
```

index.js:
```js
({
  x: function () {},
});
```

```sh
$ ./node_modules/.bin/eslint index.js

Oops! Something went wrong! :(

ESLint: 8.46.0

TypeError: Cannot read properties of null (reading 'range')
Occurred while linting /Users/michael/code/hermes-eslint-indent-error/index.js:1
Rule: "indent"
    at SourceCode.getTokenAfter (/Users/michael/code/hermes-eslint-indent-error/node_modules/eslint/lib/source-code/token-store/index.js:315:18)
    at Object.Property [as listener] (/Users/michael/code/hermes-eslint-indent-error/node_modules/eslint/lib/rules/indent.js:1400:52)
    at Program:exit (/Users/michael/code/hermes-eslint-indent-error/node_modules/eslint/lib/rules/indent.js:1722:38)
    at ruleErrorHandler (/Users/michael/code/hermes-eslint-indent-error/node_modules/eslint/lib/linter/linter.js:1050:28)
    at /Users/michael/code/hermes-eslint-indent-error/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/michael/code/hermes-eslint-indent-error/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/michael/code/hermes-eslint-indent-error/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/michael/code/hermes-eslint-indent-error/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.leaveNode (/Users/michael/code/hermes-eslint-indent-error/node_modules/eslint/lib/linter/node-event-generator.js:349:14)
```

## Steps To Reproduce

A minimal reproduction (same as above, but for convenience) is at https://github.com/mwiencek/hermes-eslint-indent-error

**Comment by pieterv** [comment]
Thanks for the great repro and easy to follow details! I coincidentally had already fixed this as part of a refactor for the next release so i was able to test it worked with your https://github.com/mwiencek/hermes-eslint-indent-error repo, which it did! Ill put up the PR soon with the fix and i am targeting next week for the release.

In the meantime if you did wanna patch it locally you can replace the `mapProperty` function in the `dist/HermesToESTreeAdapter.js` file within the `hermes-parser` package with the following code:
```

  mapProperty(nodeUnprocessed) {
    const node = this.mapNodeDefault(nodeUnprocessed);

    if (
      node.value.type === 'FunctionExpression' &&
      (node.method || node.kind !== 'init')
    ) {
      node.value.loc.start = node.key.loc.end;
      node.value.range[0] = node.key.range[1];
    }

    return node;
  }
```
