### ISSUE TITLE
Many libraries can cause "Error.stack getter called with an invalid receiver"

### ISSUE THREAD

**Issue by thomasttvo** [facebook/hermes#1496]
## Bug Description

When an error is thrown while rendering, RN crashes of course as expected. However, for some errors, when `ExceptionsManager` calls `error.stack`, it throws new errors, masking the original errors, which makes it impossible to know what the original error was for users in production (using tools like sentry). 

This happens when libraries using a technique like this to create their error classes:

```ts
    const MyError = function(message) {
      this.message = message;
    };
    MyError.prototype = new Error;
    MyError.prototype.name = 'MyError';
```

I can find at least 5 popular libraries that use this technique, and if it works in classic JS, I think it's supposed to work with hermes?

- [x] The issue is reproducible with the latest version of React Native.

React Native version: 0.73.5
OS: iOS, Android

## Steps To Reproduce

```ts
 useEffect(() => {
    const MyError = function(message) {
      this.message = message;
    };
    MyError.prototype = new Error;
    MyError.prototype.name = 'MyError';

    throw new MyError('1234')
  }, []);

```

## The Expected Behavior

Calling `new MyError().stack` doesn't throw `Error.stack getter called with an invalid receiver`

**Comment by tmikov** [comment]
@thomasttvo hi, `Error.stack` is not part of the ECMAScript spec, so any behavior is valid. However, the example you have shared doesn't seem to work in any engine. I just tried the following:

```js
const MyError = function(message) {
      this.message = message;
    };
    MyError.prototype = new Error;
    MyError.prototype.name = 'MyError';


function foo() {
    throw new MyError('1234')
}
function bar() {
    foo();
}


try {
    bar();
} catch (e) {
    print(e.stack);
}
```

If you run it with v8 or jsc, you get a useless stack trace:
```
v8 test.js
MyError
    at test.js:4:25
```

So, why is this a useful?

**Comment by thomasttvo** [comment]
@tmikov Even though the error doesn't report the stack trace that points to where it is actually thrown, it's useful enough to find out which library it comes from. We have no control over what libraries do with their errors, some throw plain objects, some throw strings. In any of those cases, **_some_** info is good enough, whereas the stack trace of `error.stack` provides no useful info
![image](https://github.com/user-attachments/assets/a9a38edb-8615-4d72-abad-e1d0341ee06a)

**Comment by tmikov** [comment]
@thomasttvo Do you have an explanation of what the point is of putting an Error object in the prototype? What does it accomplish? More importantly, is there a formal specification anywhere of how this should work?

**Comment by thomasttvo** [comment]
@tmikov I believe these libraries originated from a time pre-ES6 when class inheritance wasn't a feature. That was how you do class inheritance back then.

**Comment by tmikov** [comment]
@thomasttvo this is most definitely not how inheritance was implemented pre-ES5. At the very least it should call the parent constructor.

**Comment by tmikov** [comment]
We understand this is a real problem users of Hermes are having and we want to help. But we need to understand what the solution is.

**Comment by thomasttvo** [comment]
@tmikov you're right, that's not how you're supposed to do inheritance, but many libraries use that method, but it didn't throw any error. I think the fix is to display the stack trace of the original error in the prototype and avoid throwing further errors when you perform operations on `Error`. If that's impossible, then just return the string  `"Error.stack getter called with an invalid receiver"` from the stack would be great.

**Comment by tmikov** [comment]
@thomasttvo yes, I think I am beginning to get the picture. One way or another we will make sure the `stack` getter doesn't throw.

**Comment by thomasttvo** [comment]
thank you! with that said, if the stack getter returns `at test.js:4:25` like above, it would be really really helpful 🙏 although I know this might be hard to achieve.

**Comment by tmikov** [comment]
This is the fix, landing in Static Hermes. The getter returns the stack from the prototype.

**Comment by wobsoriano** [comment]
@tmikov looks like the fix was cancelled?

**Comment by tmikov** [comment]
> @tmikov looks like the fix was cancelled?

It wasn't cancelled. As can be seen clearly above, it was committed in https://github.com/facebook/hermes/pull/1497

**Comment by wobsoriano** [comment]
I see, so it was just labeled "Closed" but it's merged?

**Comment by tmikov** [comment]
@wobsoriano yeah, I am not sure why it doesn't say "Merged", when it clearly was:

<img width="880" alt="Screenshot 2024-09-08 at 9 03 03 AM" src="https://github.com/user-attachments/assets/8d0eb104-66d3-4e1e-8dcf-f03b5ff7f660">

**Comment by wobsoriano** [comment]
Thanks @tmikov! and this is not in the latest RN release right?

**Comment by tmikov** [comment]
@wobsoriano it will be in RN 0.76

**Comment by benjamin-sweney** [comment]
I am on 0.76.6 and experiencing numerous of these errors in my production application. @tmikov can you please confirm this did indeed make it into 0.76? If yes then I will open another ticket to understand this issue further.

**Comment by tmikov** [comment]
@benjamin-sweney if you click on the commit, you can see the release tags it is in: https://github.com/facebook/hermes/commit/db6d12e202e15f7a446d8848d6ca8f7abb3cfb32

It is definitely in 0.76.

**Comment by tmikov** [comment]
@exzos28 if you can provide a standalone reproduction, we will look into it.

Also, please keep in mind that this pattern is objectively bad code, it isn't spec-compliant, and it should always be avoided in new code. But we do understand that old libraries relying on it exist.

**Comment by exzos28** [comment]
@tmikov 

from mobx:
```
export function FlowCancellationError() {
    this.message = “FLOW_CANCELLED”
}
FlowCancellationError.prototype = Object.create(Error.prototype)
```

then:
```
throw new FlowCancellationError()
```

and try to read:
```
try {
...
} catch (error) {
   error.stack // fatal
}
```

**Comment by tmikov** [comment]
@exzos28 thank you, I see the problem. We will fix it.

Note that it doesn't "fatal" - it correctly throws an exception that the getter is applied to an incorrect target, namely an Object, when it should be applied to an instance of Error.

**Comment by exzos28** [comment]
@tmikov "fatal" - I meant it would crash the application.

**Comment by tmikov** [comment]
> [@tmikov](https://github.com/tmikov) "fatal" - I meant it would crash the application.

Sorry, I am not sure why a JS exception crashes the application. But it doesn't really matter.

**Comment by exzos28** [comment]
@tmikov 
It's not the JS exception that crashes the application, it's the attempt to read the stack property. 

My case is that I have an unhandled `FlowCancellationError` exception, it goes to the global scrope where Sentry gets it.

Next [from](https://github.com/getsentry/sentry-react-native/blob/cec511e3f1e144e0291a34d6d408165c34435e3e/packages/core/src/js/utils/error.ts#L37) sentry code:

```
...
typeof potentialError.stack === 'string'
...
```

This throws `Error.stack getter called with an invalid receiver`

**Comment by tmikov** [comment]
The fix is in: https://github.com/facebook/hermes/pull/1621

**Comment by tmikov** [comment]
> thank you! with that said, if the stack getter returns `at test.js:4:25` like above, it would still be really really helpful 🙏 although I know this might be hard to achieve.

@thomasttvo turns out you were right, sorry! 😢
