### ISSUE TITLE
After migration to React Native 62 - app crashed if Hermes enabled

### ISSUE THREAD

**Issue by alexkrav** [facebook/hermes#246]
After migration to React Native 62 - app crashed if Hermes enabled (see file attached).
[hermes_crash.txt](https://github.com/facebook/hermes/files/4646504/hermes_crash.txt)
It worked ok with RN 61.
At the beginning in log there were unexpected:
![image](https://user-images.githubusercontent.com/1795751/82247195-d621b280-98fa-11ea-98ad-9a0e8aeb5dd6.png)

Please help.
Thank you

**Comment by info-bit** [comment]
Same issue here. It happens also with a clean native project just initiated.

**Comment by Josh2941** [comment]
Same problem for me too. I migrated my project from 0.59.10 to 0.62.2. But it works fine when I created a new sample project with `react-native init` and enabling hermes for it. Need a fix for this issue since it's a breaking problem.

**Comment by dulinriley** [comment]
I think the SoLoader errors at the beginning are misleading, since the actual crash appears to be a SIGSEGV somewhere deep within Hermes.

To triage this, we'll need to have a symbolicated stack trace to know where the error occurs.
@alexkrav can you help us get a stack trace?

You'll need to rebuild your app with a version of Hermes that includes debugging symbols. The only way to do that for now is to build Hermes from source and re-build your app with a debug version of `libhermes.so`.

@willholen knows the most about building from source in RN.

**Comment by dulinriley** [comment]
If anyone is seeing errors related to `libjsc.so` that are not a SIGSEGV in Hermes, you'll want to read issue #78 (and the other linked issues from that issue).

**Comment by nes123** [comment]
is hermes 0.5.0 supported by react native 0.62?

**Comment by avp** [comment]
Hermes 0.5.0 is only supported for RN 0.63.x. See the [releases](https://github.com/facebook/hermes/releases/tag/v0.5.0) page.

**Comment by alexkrav** [comment]
Migrated to 0.63.0; after setup Hermes and polyfill types , got exceptions:
```
2020-07-15 15:35:36.248 28258-28424/com.evernote E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    com.facebook.jni.UnknownCppException: Unknown
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:237)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
2020-07-15 15:35:36.249 28258-28424/com.evernote E/unknown:ReactNative: Exception in native call
    com.facebook.jni.UnknownCppException: Unknown
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:237)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
2020-07-15 15:35:36.269 28258-28424/com.evernote E/ReactNativeJNI: Attempting to call JS function on a bad application bundle: HMRClient.setup()
2020-07-15 15:35:36.271 28258-28424/com.evernote E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: HMRClient.setup()
.....
2020-07-15 15:35:36.271 28258-28424/com.evernote E/ReactNativeJNI: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
.....
2020-07-15 15:35:36.273 28258-28424/com.evernote E/ReactNativeJNI: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
.....
2020-07-15 15:35:36.274 28258-28424/com.evernote E/ReactNativeJNI: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
....
```

**Comment by alexkrav** [comment]
as far as different case and exceptions for  RN 0.63.0 - created separate ticket  -  #298

**Comment by dulinriley** [comment]
If I'm reading this right, it sounds like the original issue was fixed by making sure the Hermes version matched the corresponding React Native version. The issue with Hermes 0.5 and RN 0.63 is in a separate issue now.

As for the difficulty in figuring out what the native stack was when a crash happens, we're looking into a way to improve this for the next Hermes release.

**Comment by inmogr** [comment]
I have
```
"react": "17.0.1",
"react-native": "0.64.1",
```

I'm having the same issue only when enabling hermes. so for the time being I had to disable hermes and the app works perfectly. But I need hermes for better app performance, so kindly help

**Comment by essana3** [comment]
Same issue here
