### ISSUE TITLE
undefined is not a function, js engine: hermes

### ISSUE THREAD

**Issue by sunpandeydeloitte** [facebook/hermes#273]
Description:
We updated to RN-0.61.5 and in production we are getting these crashes. We tested our android app and it is working fine for us, but in production we are getting many crashes

Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: undefined is not a function, js engine: hermes, stack:
anonymous (address at@1:1082033
apply@-1
anonymous (address at@1:173481
y (address at@1:172762
callTimers (address at@1:174535
apply@-1
value (address at@1:61790
anonymous (address at@1:60213
value (address at@1:61388
value (address at@1:60171

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:214)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
       at java.lang.Thread.run(Thread.java:764)

**Comment by vinayjags** [comment]
I am also facing the same, issue.. can fixes for the same.

**Comment by willholen** [comment]
Could you please symbolicate the stack trace so it's easier to see where the problem is? 

I don't know of a better way than checking out the source at the right revision, doing a release build to generatet the source maps, then using `metro-symbolicate` on each line/column, e.g.

`npx metro-symbolicate android/app/build/generated/sourcemaps/react/release/index.android.bundle.map 1 1082033`

**Comment by willholen** [comment]
As an update, the tool does support an easier invocation to symbolicate everything in one go:

    npx metro-symbolicate android/app/build/generated/sourcemaps/react/release/index.android.bundle.map < stacktrace.txt

(stdin must not be a tty, otherwise it exits immediately)

**Comment by sunpandeydeloitte** [comment]
After disabling hermes in prod. i got proper error message.
