### ISSUE TITLE
RN 0.63.1 and enableHermes leads to quit on start

### ISSUE THREAD

**Issue by Hamza-Jd** [facebook/hermes#325]
## Bug Description

The app quits directly after the debug release is installed

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.6.0
React Native version: 0.63.1
Android version: 9
Platform: arm64-v8a

`build.gradle`

```
project.ext.react = [
    enableHermes: true, // clean and rebuild if changing
]


if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
} else {
        implementation jscFlavor
}
```

### logs

after running `yarn android` and `npx react-native log-android`

```
[03:28:25] I | ReactNativeJS ▶︎ Running "ReactNativeTemplateTs" with {"rootTag":1}

[03:28:26] I | ReactNative ▶︎ [GESTURE HANDLER] Initialize gesture handler for root view com.facebook.react.ReactRootView{7c95b2b V.E...... ......ID 0
,0-1080,2190 #1}

[03:29:10] W | ReactNativeJS ▶︎ Cannot connect to the Metro server.
                             │ 
                             │ Try the following to fix the issue:
                             │ - Ensure that the Metro server is running and available on the same network
                             │ - Ensure that your device/emulator is connected to your machine and has USB debugging enabled - run 'adb devices' to see a list of connected devices
                             │ - If you're on a physical device connected to the same machine, run 'adb reverse tcp:8081 tcp:8081' to forward requests from your device
                             │ - If your device is on the same Wi-Fi network, set 'Debug server host & port for device' in 'Dev settings' to your machine's IP address and the port of the local dev server - e.g. 10.0.1.1:8081
                             │
                             │ URL: localhost:8081
                             │
                             └ Error: null
```
Note: Tried to use the hermes that comes with react native and tried using it as a dev dependency after running `yarn add --dev hermes-engine`

**Comment by mrousavy** [comment]
Same issue here! Apparently the bundle is not being built, because after I ran:

```sh
npx react-native bundle --platform android --dev true --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
```

And re-ran the app everything worked fine.

**Comment by Hamza-Jd** [comment]
@mrousavy yes, the is behaving normally without hermes

**Comment by mrousavy** [comment]
I've just compared my Logcat outputs (JSC vs Hermes) and noticed that in Hermes the following Stacktrace gets shown:

```
2020-08-12 14:53:13.871 14020-14197/com.mrousavy.springsale D/SoLoader: About to load: libhermes.so
2020-08-12 14:53:13.872 14020-14197/com.mrousavy.springsale D/SoLoader: libhermes.so not found on /data/data/com.mrousavy.springsale/lib-main
2020-08-12 14:53:13.872 14020-14197/com.mrousavy.springsale D/SoLoader: libhermes.so found on /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86
2020-08-12 14:53:13.872 14020-14197/com.mrousavy.springsale D/SoLoader: Not resolving dependencies for libhermes.so
2020-08-12 14:53:13.874 14020-14197/com.mrousavy.springsale D/SoLoader: Loaded: libhermes.so
2020-08-12 14:53:13.874 14020-14197/com.mrousavy.springsale D/SoLoader: About to load: libhermes-executor-debug.so
2020-08-12 14:53:13.874 14020-14197/com.mrousavy.springsale D/SoLoader: libhermes-executor-debug.so not found on /data/data/com.mrousavy.springsale/lib-main
2020-08-12 14:53:13.875 14020-14197/com.mrousavy.springsale D/SoLoader: libhermes-executor-debug.so found on /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86
2020-08-12 14:53:13.875 14020-14197/com.mrousavy.springsale D/SoLoader: Not resolving dependencies for libhermes-executor-debug.so
2020-08-12 14:53:13.885 14020-14197/com.mrousavy.springsale D/SoLoader: Loaded: libhermes-executor-debug.so
2020-08-12 14:53:13.988 14020-14197/com.mrousavy.springsale I/RNFusedLocation: RNFusedLocation initialized
2020-08-12 14:53:14.010 1778-14198/? E/ResolverController: No valid NAT64 prefix (102, <unspecified>/0)
2020-08-12 14:53:14.090 1794-2257/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2020-08-12 14:53:14.090 1794-2257/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
2020-08-12 14:53:14.645 14020-14020/com.mrousavy.springsale W/mqt_js: type=1400 audit(0.0:482): avc: denied { search } for name="power_supply" dev="sysfs" ino=13712 scontext=u:r:untrusted_app:s0:c154,c256,c512,c768 tcontext=u:object_r:sysfs_batteryinfo:s0 tclass=dir permissive=0
2020-08-12 14:53:14.676 14020-14200/com.mrousavy.springsale A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb000002 in tid 14200 (mqt_js), pid 14020 (savy.springsale)
2020-08-12 14:53:14.749 14206-14206/? I/crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
2020-08-12 14:53:14.750 1866-1866/? I//system/bin/tombstoned: received crash request for pid 14200
2020-08-12 14:53:14.751 14206-14206/? I/crash_dump32: performing dump of process 14020 (target tid = 14200)
2020-08-12 14:53:14.758 14206-14206/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-08-12 14:53:14.758 14206-14206/? A/DEBUG: Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:user/release-keys'
2020-08-12 14:53:14.758 14206-14206/? A/DEBUG: Revision: '0'
2020-08-12 14:53:14.758 14206-14206/? A/DEBUG: ABI: 'x86'
2020-08-12 14:53:14.758 14206-14206/? A/DEBUG: Timestamp: 2020-08-12 14:53:14+0200
2020-08-12 14:53:14.758 14206-14206/? A/DEBUG: pid: 14020, tid: 14200, name: mqt_js  >>> com.mrousavy.springsale <<<
2020-08-12 14:53:14.758 14206-14206/? A/DEBUG: uid: 10154
2020-08-12 14:53:14.758 14206-14206/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb000002
2020-08-12 14:53:14.758 14206-14206/? A/DEBUG:     eax 0b000002  ebx b2fbc8c4  ecx d1fda6a0  edx bb82b9c8
2020-08-12 14:53:14.759 14206-14206/? A/DEBUG:     edi d1fda638  esi bb82b9e8
2020-08-12 14:53:14.759 14206-14206/? A/DEBUG:     ebp bb82b8c8  esp bb82b890  eip b2c6fee5
2020-08-12 14:53:14.903 14206-14206/? A/DEBUG: backtrace:
2020-08-12 14:53:14.904 14206-14206/? A/DEBUG:       #00 pc 00029ee5  /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86/libhermes.so (BuildId: 369958083505a2193408b1184eb457ede14ba5d5)
2020-08-12 14:53:14.904 14206-14206/? A/DEBUG:       #01 pc 000299e9  /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86/libhermes.so (hermes::vm::RuntimeConfig::RuntimeConfig(hermes::vm::RuntimeConfig const&)+41) (BuildId: 369958083505a2193408b1184eb457ede14ba5d5)
2020-08-12 14:53:14.904 14206-14206/? A/DEBUG:       #02 pc 000291d3  /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86/libhermes.so (facebook::hermes::HermesRuntimeImpl::HermesRuntimeImpl(hermes::vm::RuntimeConfig const&)+339) (BuildId: 369958083505a2193408b1184eb457ede14ba5d5)
2020-08-12 14:53:14.904 14206-14206/? A/DEBUG:       #03 pc 0001fe94  /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86/libhermes.so (facebook::hermes::makeHermesRuntime(hermes::vm::RuntimeConfig const&)+52) (BuildId: 369958083505a2193408b1184eb457ede14ba5d5)
2020-08-12 14:53:14.904 14206-14206/? A/DEBUG:       #04 pc 0001a26c  /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86/libhermes-executor-debug.so (facebook::react::HermesExecutorFactory::createJSExecutor(std::__ndk1::shared_ptr<facebook::react::ExecutorDelegate>, std::__ndk1::shared_ptr<facebook::react::MessageQueueThread>)+60) (BuildId: 9dce540e51aa69e247c03db8c17722fa203a0b70)
2020-08-12 14:53:14.904 14206-14206/? A/DEBUG:       #05 pc 0009c2c8  /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86/libreactnativejni.so (facebook::react::NativeToJsBridge::NativeToJsBridge(facebook::react::JSExecutorFactory*, std::__ndk1::shared_ptr<facebook::react::ModuleRegistry>, std::__ndk1::shared_ptr<facebook::react::MessageQueueThread>, std::__ndk1::shared_ptr<facebook::react::InstanceCallback>)+216) (BuildId: 930803d0b368271f5f896b0cefe51d5c5c2e92b3)
2020-08-12 14:53:14.904 14206-14206/? A/DEBUG:       #06 pc 00093fca  /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86/libreactnativejni.so (_ZNSt6__ndk122__compressed_pair_elemIN8facebook5react16NativeToJsBridgeELi1ELb0EEC2IJOPNS2_17JSExecutorFactoryERNS_10shared_ptrINS2_14ModuleRegistryEEERNS9_INS2_18MessageQueueThreadEEERNS9_INS2_16InstanceCallbackEEEEJLj0ELj1ELj2ELj3EEEENS_21piecewise_construct_tENS_5tupleIJDpT_EEENS_15__tuple_indicesIJXspT0_EEEE+154) (BuildId: 930803d0b368271f5f896b0cefe51d5c5c2e92b3)
2020-08-12 14:53:14.904 14206-14206/? A/DEBUG:       #07 pc 00093d06  /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86/libreactnativejni.so (BuildId: 930803d0b368271f5f896b0cefe51d5c5c2e92b3)
2020-08-12 14:53:14.904 14206-14206/? A/DEBUG:       #08 pc 00062089  /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86/libreactnativejni.so (BuildId: 930803d0b368271f5f896b0cefe51d5c5c2e92b3)
2020-08-12 14:53:14.904 14206-14206/? A/DEBUG:       #09 pc 0005fe15  /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86/libreactnativejni.so (BuildId: 930803d0b368271f5f896b0cefe51d5c5c2e92b3)
2020-08-12 14:53:14.904 14206-14206/? A/DEBUG:       #10 pc 0004ee42  /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86/libreactnativejni.so (_ZN8facebook3jni6detail13MethodWrapperIMNS_5react15JNativeRunnableEFvvEXadL_ZNS4_3runEvEES4_vJEE8dispatchENS0_9alias_refIPNS1_8JTypeForINS0_11HybridClassIS4_NS3_8RunnableEE8JavaPartESB_vE11_javaobjectEEE+50) (BuildId: 930803d0b368271f5f896b0cefe51d5c5c2e92b3)
2020-08-12 14:53:14.904 14206-14206/? A/DEBUG:       #11 pc 0004eda9  /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86/libreactnativejni.so (_ZN8facebook3jni6detail15FunctionWrapperIPFvNS0_9alias_refIPNS1_8JTypeForINS0_11HybridClassINS_5react15JNativeRunnableENS6_8RunnableEE8JavaPartES8_vE11_javaobjectEEEEXadL_ZNS1_13MethodWrapperIMS7_FvvEXadL_ZNS7_3runEvEES7_vJEE8dispatchESE_EESD_vJEE4callEP7_JNIEnvP8_jobject+73) (BuildId: 930803d0b368271f5f896b0cefe51d5c5c2e92b3)
2020-08-12 14:53:14.905 14206-14206/? A/DEBUG:       #12 pc 0004ed53  /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/lib/x86/libreactnativejni.so (_ZN8facebook3jni6detail13MethodWrapperIMNS_5react15JNativeRunnableEFvvEXadL_ZNS4_3runEvEES4_vJEE4callEP7_JNIEnvP8_jobject+35) (BuildId: 930803d0b368271f5f896b0cefe51d5c5c2e92b3)
2020-08-12 14:53:14.905 14206-14206/? A/DEBUG:       #13 pc 00144f67  /apex/com.android.runtime/lib/libart.so (art_quick_generic_jni_trampoline+71) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.905 14206-14206/? A/DEBUG:       #14 pc 02027092  /memfd:/jit-cache (deleted) (android.os.Handler.handleCallback+66)
2020-08-12 14:53:14.905 14206-14206/? A/DEBUG:       #15 pc 020310b1  /memfd:/jit-cache (deleted) (android.os.Handler.dispatchMessage+65)
2020-08-12 14:53:14.905 14206-14206/? A/DEBUG:       #16 pc 0013e7d2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.905 14206-14206/? A/DEBUG:       #17 pc 00149a69  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+281) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.905 14206-14206/? A/DEBUG:       #18 pc 00332502  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+386) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.905 14206-14206/? A/DEBUG:       #19 pc 0032c19c  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+988) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.905 14206-14206/? A/DEBUG:       #20 pc 00682731  /apex/com.android.runtime/lib/libart.so (MterpInvokeSuper+1841) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.905 14206-14206/? A/DEBUG:       #21 pc 001388a1  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_super+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.905 14206-14206/? A/DEBUG:       #22 pc 003ee8e4  [anon:dalvik-classes.dex extracted in memory from /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/base.apk] (com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #23 pc 002f8e0a  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.12194892193087984976+298) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #24 pc 002ffcc5  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+181) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #25 pc 0066fbd9  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+1209) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #26 pc 0014503d  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+77) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #27 pc 020112a1  /memfd:/jit-cache (deleted) (android.os.Looper.loop+1553)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #28 pc 0013e9a2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_static_stub+418) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #29 pc 00149a7a  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+298) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #30 pc 00332502  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+386) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #31 pc 002f8f37  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.12194892193087984976+599) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #32 pc 002ffe19  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+217) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #33 pc 0032c17e  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+958) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #34 pc 00684d03  /apex/com.android.runtime/lib/libart.so (MterpInvokeStatic+643) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #35 pc 001389a1  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_static+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #36 pc 003eea72  [anon:dalvik-classes.dex extracted in memory from /data/app/com.mrousavy.springsale-MhkPsI0hCQqI4EZ0tEuYNQ==/base.apk] (com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run+74)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #37 pc 006837bc  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1980) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #38 pc 00138a21  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.906 14206-14206/? A/DEBUG:       #39 pc 000ea918  /apex/com.android.runtime/javalib/core-oj.jar (java.lang.Thread.run+8)
2020-08-12 14:53:14.907 14206-14206/? A/DEBUG:       #40 pc 002f8e0a  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.12194892193087984976+298) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.907 14206-14206/? A/DEBUG:       #41 pc 002ffcc5  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+181) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.907 14206-14206/? A/DEBUG:       #42 pc 0066fbd9  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+1209) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.907 14206-14206/? A/DEBUG:       #43 pc 0014503d  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+77) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.907 14206-14206/? A/DEBUG:       #44 pc 0013e7d2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.907 14206-14206/? A/DEBUG:       #45 pc 00149a69  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+281) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.907 14206-14206/? A/DEBUG:       #46 pc 0055a513  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+99) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.907 14206-14206/? A/DEBUG:       #47 pc 0055b91a  /apex/com.android.runtime/lib/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+474) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.907 14206-14206/? A/DEBUG:       #48 pc 005aaa51  /apex/com.android.runtime/lib/libart.so (art::Thread::CreateCallback(void*)+1585) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 14:53:14.907 14206-14206/? A/DEBUG:       #49 pc 0011a8e5  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+53) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
2020-08-12 14:53:14.907 14206-14206/? A/DEBUG:       #50 pc 000af6a7  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+71) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
2020-08-12 14:53:15.090 1794-2257/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2020-08-12 14:53:15.090 1794-2257/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
2020-08-12 14:53:15.546 1866-1866/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_04
```

and some lines later:

```
2020-08-12 14:53:16.145 21886-21919/? E/ModuleIdSetter: exception when setting module id
    java.lang.IllegalStateException: Unable to get current module info in ModuleManager created with non-module Context
        at com.google.android.chimera.config.ModuleManager.getCurrentModule(:com.google.android.gms@202414040@20.24.14 (120700-319035315):2)
        at aeua.a(:com.google.android.gms@202414040@20.24.14 (120700-319035315):4)
        at aeud.b(:com.google.android.gms@202414040@20.24.14 (120700-319035315):9)
        at aeql.a(Unknown Source:0)
        at rnb.a(:com.google.android.gms@202414040@20.24.14 (120700-319035315):0)
        at rjk.c(:com.google.android.gms@202414040@20.24.14 (120700-319035315):1)
        at rji.b(:com.google.android.gms@202414040@20.24.14 (120700-319035315):1)
        at rlz.b(:com.google.android.gms@202414040@20.24.14 (120700-319035315):6)
        at rlz.c(:com.google.android.gms@202414040@20.24.14 (120700-319035315):6)
        at rlz.b(:com.google.android.gms@202414040@20.24.14 (120700-319035315):10)
        at rlz.a(:com.google.android.gms@202414040@20.24.14 (120700-319035315):17)
        at rlz.g(:com.google.android.gms@202414040@20.24.14 (120700-319035315):3)
        at sbg.a(:com.google.android.gms@202414040@20.24.14 (120700-319035315):2)
        at sag.a(:com.google.android.gms@202414040@20.24.14 (120700-319035315):10)
        at rzx.a(:com.google.android.gms@202414040@20.24.14 (120700-319035315):0)
        at saa.handleMessage(:com.google.android.gms@202414040@20.24.14 (120700-319035315):28)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at aeiw.a(:com.google.android.gms@202414040@20.24.14 (120700-319035315):2)
        at aeiw.dispatchMessage(:com.google.android.gms@202414040@20.24.14 (120700-319035315):14)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

then the app crashes.

**Comment by avp** [comment]
This is likely crashing because Hermes 0.6.0 is only supported for RN 0.64.x.

See the [releases page](https://github.com/facebook/hermes/releases/tag/v0.6.0) for more information.

**Comment by mrousavy** [comment]
@avp I'm not on 0.6.0, should I open a separate issue?

**Comment by avp** [comment]
@mrousavy Sure, in the interest of categorizing separate problems, make a new issue. Please be sure to fill out your version information, and go ahead link the stack traces you listed here. Thanks!

**Comment by Hamza-Jd** [comment]
@avp i tried both 0.5 and 0.6 and the two of made the app to quit on start

**Comment by Eli-Nathan** [comment]
Should this reopen? I'm having the same issue. It's completely halted my development work 😞

Tried Hermes version 0.1.1 -> 0.6.0 and app quits immediately on all of them.

**Comment by lucaswhitman** [comment]
> @avp I'm not on 0.6.0, should I open a separate issue?

@mrousavy did you ever find a solution here? I didn't see a new issue, and this one's closed but definitely still crashing for me.
