### ISSUE TITLE
Error Hermes with React-Native 0.63.3 and librairie React-native-jitsi-meet

### ISSUE THREAD

**Issue by Marinaarimany** [facebook/hermes#402]
Hello,

I have this error when I want to launch my Visio application in native React, it crashes directly. I use the react-native-jitsi-meet library (version 2.1.1) which uses jitsi's sdk in version 2.4.0. I have been having problems with Hermès (version 0.7.1) for several weeks.
Can someone help me please?

```
SoLoader: couldn't find DSO to load: libhermes.so result: 0
2020-11-04 16:00:36.958 5240-5285/com.test E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.test, PID: 5240
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:825)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:611)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:559)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1017)
        at java.lang.Thread.run(Thread.java:929)
```

My build.gradle (app)

```
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation. If none specified and
 *   // "index.android.js" exists, it will be used. Otherwise "index.js" is
 *   // default. Can be overridden with ENTRY_FILE environment variable.
 *   entryFile: "index.android.js",
 *
 *   // https://reactnative.dev/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
        entryFile: "index.js",
        enableHermes: false,  // clean and rebuild if changing
        hermesCommand: "../../node_modules/hermes-engine/osx-bin/hermes",
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.test"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        ndk { abiFilters "armeabi-v7a", "x86", "arm64-v8a", "x86_64" }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
    def taskName = getGradle().getStartParameter().getTaskRequests().toString()


    packagingOptions {
        pickFirst "lib/armeabi-v7a/libc++_shared.so"
        pickFirst "lib/arm64-v8a/libc++_shared.so"
        pickFirst "lib/x86/libc++_shared.so"
        pickFirst "lib/x86_64/libc++_shared.so"
        //pickFirst '**/armeabi-v7a/libc++_shared.so'
        //pickFirst '**/x86/libc++_shared.so'
        //pickFirst '**/x86_64/libc++_shared.so'
        //pickFirst '**/arm64-v8a/libc++_shared.so'
        //pickFirst '**/libjsc.so'
//
        //pickFirst '**/libhermes-inspector.so'
        //pickFirst '**/libjscexecutor.so'
        //pickFirst '**/lib-main/libhermes-inspector.so'
      //  exclude '**/libhermes-inspector.so'
        exclude '**/libjscexecutor.so'
      //  exclude "lib/arm64-v8a/libgnustl_shared.so"
      //  exclude '/lib/mips64/**'
      //  exclude '/lib/arm64-v8a/**'
      //  exclude '/lib/x86_64/**'

        exclude "**/libjsc*.so"
        if (taskName.contains("InternalDebug")) {
            // Release libs take precedence and must be removed
            // to allow debugging
            exclude '**/libhermes-executor-release.so'
        } else {
            // Reduce size by deleting the debugger/inspector
            exclude '**/libhermes-inspector.so'
            exclude '**/libhermes-executor-debug.so'
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation 'com.facebook.soloader:soloader:0.9.0+'

    configurations.all {
        resolutionStrategy {
            force "com.facebook.soloader:soloader:0.8.2"
        }
    }
    implementation 'androidx.appcompat:appcompat:1.2.0'

    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation("com.facebook.infer.annotation:infer-annotation:0.11.2")
    implementation("javax.inject:javax.inject:1")
    implementation "androidx.appcompat:appcompat:1.0.0"
    implementation "androidx.localbroadcastmanager:localbroadcastmanager:1.0.0"
    implementation("com.facebook.fresco:fresco:2.2.0")
    implementation("com.facebook.fresco:imagepipeline-okhttp3:2.0.0")
    implementation("com.facebook.soloader:soloader:0.9.0")
    implementation("com.google.code.findbugs:jsr305:3.0.2")
    implementation("com.squareup.okhttp3:okhttp:3.14.1")
    implementation("com.squareup.okhttp3:okhttp-urlconnection:3.12.1")
    implementation("com.squareup.okio:okio:1.17.2")

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    implementation(project(':react-native-jitsi-meet')) {
        //exclude group: 'com.facebook.react',module:'react-native-vector-icons'
        //exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
        exclude group: 'com.facebook',module:'hermes'
        transitive = true

    }
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

Thank you !

**Comment by dulinriley** [comment]
I noticed your `build.gradle` file has the following:
```
project.ext.react = [
        entryFile: "index.js",
        enableHermes: false,  // clean and rebuild if changing
        hermesCommand: "../../node_modules/hermes-engine/osx-bin/hermes",
]
```
But you say you're using Hermes. Have you tried changing that to `true` and doing `gradle clean` before rebuilding?

**Comment by Marinaarimany** [comment]
Hello @dulinriley Yes I have already tried and I am still stuck with the same type error :/

**Comment by ShikaSD** [comment]
@Marinaarimany Hey, I looked into it, and seems like you have removed "non-Hermes" JSC executor with these two lines:
```
exclude '**/libjscexecutor.so'
exclude "**/libjsc*.so"
```

Commenting out these two (or enabling Hermes with `project.ext.react.enableHermes=true`) fixes the issue.
Seems like if there's no JSCExecutor among attached .so files, it falls back to Hermes, hence the confusing error message.
