### ISSUE TITLE
Git Bash Windows 10 CMake Error: Multiple -A options not allowed

### ISSUE THREAD

**Issue by dangolbeeker** [facebook/hermes#447]
Does anyone have a suggestion?

```
hermes/utils/build/configure.py --build-system='Visual Studio 16 2019' --cmake-flags='-A x64' --distribute

CMake Error: Multiple -A options not allowed
Building hermes using Visual Studio 16 2019 into C:\Users\Scott\hermes_workingdir\build_release\
CMake flags: -A x64 -DPYTHON_EXECUTABLE=C:\Python39\python.exe -DCMAKE_BUILD_TYPE=MinSizeRel -Ax64
CMake version:
b'cmake version 3.19.4\n\nCMake suite maintained and supported by Kitware (kitware.com/cmake).\n'
+ C:\Program Files\CMake\bin\cmake.EXE C:\Users\Scott\hermes_workingdir\hermes -G Visual Studio 16 2019 -A x64 -DPYTHON_EXECUTABLE=C:\Python39\python.exe -DCMAKE_BUILD_TYPE=MinSizeRel -Ax64
Traceback (most recent call last):
  File "C:\Users\Scott\hermes_workingdir\hermes\utils\build\configure.py", line 289, in <module>
    main()
  File "C:\Users\Scott\hermes_workingdir\hermes\utils\build\configure.py", line 281, in main
    run_command(
  File "C:\Users\Scott\hermes_workingdir\hermes\utils\build\configure.py", line 151, in run_command
    return subprocess.check_call(
  File "C:\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', 'C:\\Users\\Scott\\hermes_workingdir\\hermes', '-G', 'Visual Studio 16 2019', '-A', 'x64', '-DPYTHON_EXECUTABLE=C:\\Python39\\python.exe', '-DCMAKE_BUILD_TYPE=MinSizeRel', '-Ax64']' returned non-zero exit status 1.
```

**Comment by neildhar** [comment]
Sorry, it looks like the instructions are a little out of date, you no longer need to explicitly supply the target architecture on Windows. Try just:
```
hermes/utils/build/configure.py --build-system='Visual Studio 16 2019' --distribute
```

I'll update the instructions as well.

**Comment by neildhar** [comment]
Instructions updated in 1c5f487c4a8f04449da71e4c347f813e305fa4bd.
