### ISSUE TITLE
Maximum Regex stack depth reached when parseLogboxException is called using hermes with large message

### ISSUE THREAD

**Issue by dannyhw** [facebook/hermes#581]
## Bug Description

In react native when you log a large error to console.error and logbox attempts to parse it if the message is very large then the following regex throws an exception.

from `node_modules/react-native/Libraries/LogBox/Data/parseLogBoxLog.js` line 251
```
const BABEL_CODE_FRAME_ERROR_FORMAT = /^(?:TransformError )?(?:.*):? (?:.*?)(\/.*): ([\s\S]+?)\n([ >]{2}[\d\s]+ \|[\s\S]+|\u{001b}[\s\S]+)/u;

...
const babelCodeFrameError = message.match(BABEL_CODE_FRAME_ERROR_FORMAT);
```

![image](https://user-images.githubusercontent.com/3481514/130775672-e4e23a7f-d4cf-4ebe-a16a-18ffd4dee5cc.png)

Initially I thought it was a react native bug, however I've tried this when turning off hermes and using jsc and it doesn't have any issues parsing the log. 

I believe this issue is probably related also https://github.com/facebook/react-native/issues/29402

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: the one that comes with rn 0.65.1 which I believe is 0.81
React Native version (if any): 0.65.1
OS version (if any): MacOS 10.15.6
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): x86_64 

code is running on a simulator/emulator happening on both android and ios

I'm really trying to use the ndk stack tool but I don't understand the steps in the docs, I'm not able to find my abi and I'm not sure where to look or what that is 😅. I can add some of the adb log in the comments.

## Steps To Reproduce

I have created a minimal repro here https://github.com/dannyhw/hermes-regex-repro

The project was created using `npx react-native init repro --template react-native-template-typescript`

Then I enabled hermes by following the react native docs and I added some simple code to call console.error

1. clone the repro https://github.com/dannyhw/hermes-regex-repro
2. yarn install, pod install, gradle clean etc 
3. yarn ios or yarn android
4. when loading app.tsx it will attempt to log and display the logbox and parse the message which causes the exception in the screenshot

code example:

## The Expected Behavior

The regex should not fail or maybe fail gracefully somehow?

I'm happy to help but I'm not familiar with the codebase so would need guidance.

**Comment by dannyhw** [comment]
Here is a partial stack from the adb logcat output through I'm not sure how useful it is
```
08-25 11:58:17.605 10908 11201 E ReactNativeJS: 'Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi 
08-25 11:58:18.455   543   563 W WindowManager: Unable to start animation, surface is null or no children.
08-25 11:58:20.174  1248  1283 I PeriodicStatsRunner: PeriodicStatsRunner.call():180 call()
08-25 11:58:20.174  1248  1283 I PeriodicStatsRunner: PeriodicStatsRunner.call():184 No submit PeriodicStats since input started.
08-25 11:58:27.941   543   543 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@bbb9b4e
08-25 11:58:40.709   488   488 E wifi_forwarder: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:wififorward' service: Invalid argument
08-25 11:58:40.710   488   488 E wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe
08-25 11:58:54.855   543   560 E JobScheduler.Background: App com.google.android.gms became active but still in NEVER bucket
08-25 11:58:54.858   543   570 I DropBoxManagerService: add tag=system_server_wtf isTagEnabled=true flags=0x2
08-25 11:58:54.860 23758  9680 E WakeLock: GCM_HB_ALARM release without a matched acquire!
08-25 11:58:56.868   543   570 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
08-25 11:58:56.868   543   570 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
08-25 11:59:00.007   709   709 D KeyguardClockSwitch: Updating clock: 1159
08-25 11:59:04.517 10908 11201 E ReactNativeJS: RangeError: An error was thrown when attempting to render log messages via LogBox.
08-25 11:59:04.517 10908 11201 E ReactNativeJS: 
08-25 11:59:04.517 10908 11201 E ReactNativeJS: Maximum regex stack depth reached, js engine: hermes
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:66)
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:40)
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:190)
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at java.lang.Thread.run(Thread.java:923)
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:66)
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:40)
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:190)
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at java.lang.Thread.run(Thread.java:923)
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:66)
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:40)
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:190)
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at java.lang.Thread.run(Thread.java:923)
08-25 11:59:04.614 10908 11115 E unknown:ReactContextBaseJavaModule: Unhandled SoftException

```

**Comment by harishgupta01** [comment]
> Here is a partial stack from the adb logcat output through I'm not sure how useful it is
> 
> ```
> 08-25 11:58:17.605 10908 11201 E ReactNativeJS: 'Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi fugiat pariatur. Tempor culpa quis non duis cillum. Aliquip enim consectetur commodo occaecat commodo id deserunt exercitation magna dolor elit in duis culpa. Esse aliqua excepteur ipsum non non occaecat voluptate et consequat veniam aliquip qui ipsum.Labore ad cupidatat dolor dolor officia consectetur voluptate veniam aute nisi 
> 08-25 11:58:18.455   543   563 W WindowManager: Unable to start animation, surface is null or no children.
> 08-25 11:58:20.174  1248  1283 I PeriodicStatsRunner: PeriodicStatsRunner.call():180 call()
> 08-25 11:58:20.174  1248  1283 I PeriodicStatsRunner: PeriodicStatsRunner.call():184 No submit PeriodicStats since input started.
> 08-25 11:58:27.941   543   543 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@bbb9b4e
> 08-25 11:58:40.709   488   488 E wifi_forwarder: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:wififorward' service: Invalid argument
> 08-25 11:58:40.710   488   488 E wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe
> 08-25 11:58:54.855   543   560 E JobScheduler.Background: App com.google.android.gms became active but still in NEVER bucket
> 08-25 11:58:54.858   543   570 I DropBoxManagerService: add tag=system_server_wtf isTagEnabled=true flags=0x2
> 08-25 11:58:54.860 23758  9680 E WakeLock: GCM_HB_ALARM release without a matched acquire!
> 08-25 11:58:56.868   543   570 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
> 08-25 11:58:56.868   543   570 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
> 08-25 11:59:00.007   709   709 D KeyguardClockSwitch: Updating clock: 1159
> 08-25 11:59:04.517 10908 11201 E ReactNativeJS: RangeError: An error was thrown when attempting to render log messages via LogBox.
> 08-25 11:59:04.517 10908 11201 E ReactNativeJS: 
> 08-25 11:59:04.517 10908 11201 E ReactNativeJS: Maximum regex stack depth reached, js engine: hermes
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:66)
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:40)
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:190)
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 08-25 11:59:04.612 10908 11115 E unknown:ReactContextBaseJavaModule: 	at java.lang.Thread.run(Thread.java:923)
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:66)
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:40)
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:190)
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 08-25 11:59:04.613 10908 11070 E unknown:ReactContextBaseJavaModule: 	at java.lang.Thread.run(Thread.java:923)
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:66)
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:40)
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:190)
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 08-25 11:59:04.613 10908 11115 E unknown:ReactContextBaseJavaModule: 	at java.lang.Thread.run(Thread.java:923)
> 08-25 11:59:04.614 10908 11115 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
> ```

Hi @dannyhw Did you any solution for the issue ?

**Comment by dannyhw** [comment]
Ended up using a console.log instead of error.

**Comment by evelant** [comment]
@dannyhw Mind creating a new issue on the RN repo? The bot over there closed it without anyone looking at it. @neildhar any way you might be able to raise this issue with the RN team in a way where it won't get ignored and summarily closed like the last time it was reported there? Thanks!

**Comment by neildhar** [comment]
I have reopened the issue in RN and will share it with the RN team.

**Comment by evelant** [comment]
@neildhar thank you! Looks like the issue on the RN repo is still locked as "resolved" despite being open. Are you able to unlock it in case further discussion is needed?
