### ISSUE TITLE
Windows build instructions are incorrect

### ISSUE THREAD

**Issue by farzonl** [facebook/hermes#723]
https://github.com/facebook/hermes/blob/f75d5a87e86c921d269ae7ada525d1c28bd373dd/README.md?plain=1#L33-L39

The -A x64 is getting propagated twice:

```cmd
python hermes/utils/build/configure.py --build-system="Visual Studio 16 2019" --cmake-flags="-A x64" --distribute
Building hermes using Visual Studio 16 2019 into \build_release\
CMake flags: -A x64 -DPYTHON_EXECUTABLE=C:\Python310\python.exe -DCMAKE_BUILD_TYPE=MinSizeRel -Ax64
CMake version:
b'cmake version 3.21.4\n\nCMake suite maintained and supported by Kitware (kitware.com/cmake).\n'
+ C:\Program Files\CMake\bin\cmake.EXE \hermes -G Visual Studio 16 2019 -A x64 -DPYTHON_EXECUTABLE=C:\Python310\python.exe -DCMAKE_BUILD_TYPE=MinSizeRel -Ax64
CMake Error: Multiple -A options not allowed
CMake Error: Run 'cmake --help' for all supported options.
Traceback (most recent call last):
  File "\hermes\utils\build\configure.py", line 285, in <module>
    main()
  File "hermes\utils\build\configure.py", line 277, in main
    run_command(
  File "\hermes\utils\build\configure.py", line 150, in run_command
    return subprocess.check_call(
  File "C:\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '\\hermes', '-G', 'Visual Studio 16 2019', '-A', 'x64', '-DPYTHON_EXECUTABLE=C:\\Python310\\python.exe', '-DCMAKE_BUILD_TYPE=MinSizeRel', '-Ax64']' returned non-zero exit status 1.
```

Also build dir is called `build_release` not `build`

**Comment by farzonl** [comment]
Also to use msbuild there should be some mention of calling "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsMSBuildCmd.bat"

**Comment by neildhar** [comment]
Hi @farzonl, thanks for reporting this. We just updated the instructions today to use a simpler build workflow which should also address the concerns you raised. Could you try the latest instructions and share if you're still running into issues?

**Comment by farzonl** [comment]
@neildhar I can already tell this will work just from reading the new build instructions. Thanks for simplifying to just cmake.
