### ISSUE TITLE
libicu-dev is a required package to build on linux

### ISSUE THREAD

**Issue by ramosquito5** [facebook/hermes#835]
Today I tried making an app using the new architecture and failed miserably.
The error I was having was 
```
> Task :ReactAndroid:hermes-engine:configureBuildForHermes
-- Found the following ICU libraries:
--   uc (required)
--   i18n (required)
--   data (required)
--   uc (required)
-- Found ICU: /usr/include (Required is at least version "52") 
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Found Python module pygments
-- Found Python module pygments.lexers.c_cpp
-- Found Python module yaml
-- CMAKE_HOST_SYSTEM_NAME = Linux
-- CMAKE_SYSTEM_NAME = Linux
-- HERMES_APPLE_TARGET_PLATFORM = 
-- CMAKE_CROSSCOMPILING = FALSE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/amonra/sandbox/fireChatvb/node_modules/react-native/ReactAndroid/hermes-engine/build/hermes

> Task :ReactAndroid:hermes-engine:buildHermes FAILED
[  3%] Built target zip
[  6%] Built target dtoa
[ 10%] Built target LLVHDemangle
[ 36%] Built target LLVHSupport
[ 36%] Built target hermesFrontEndDefs
[ 40%] Built target hermesPlatformUnicode
[ 40%] Built target hermesRegex
[ 50%] Built target hermesOptimizer
[ 63%] Built target hermesSupport
[ 66%] Built target hermesInst
[ 66%] Built target hermesADT
[ 66%] Built target hermesFlowParser
[ 70%] Built target hermesAST
[ 73%] Built target hermesParser
[ 73%] Built target hermesAST2JS
[ 76%] Built target hermesSourceMap
[ 83%] Built target hermesFrontend
[ 83%] Built target hermesBackend
[ 96%] Built target hermesHBCBackend
[100%] Built target hermesCompilerDriver

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
25 actionable tasks: 2 executed, 23 up-to-date
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


icu dir: /usr/lib/x86_64-linux-gnu
gmake[3]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libicuuc.so', needed by 'bin/hermesc'.  Stop.
gmake[2]: *** [CMakeFiles/Makefile2:3326: tools/hermesc/CMakeFiles/hermesc.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:3333: tools/hermesc/CMakeFiles/hermesc.dir/rule] Error 2
gmake: *** [Makefile:794: hermesc] Error 2

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':ReactAndroid:hermes-engine:buildHermes'.
> Process 'command '/home/amonra/Android/Sdk/cmake/3.18.1/bin/cmake'' finished with non-zero exit value 2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


icu dir: /usr/lib/x86_64-linux-gnu
gmake[3]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libicuuc.so', needed by 'bin/hermesc'.  Stop.
gmake[2]: *** [CMakeFiles/Makefile2:3326: tools/hermesc/CMakeFiles/hermesc.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:3333: tools/hermesc/CMakeFiles/hermesc.dir/rule] Error 2
gmake: *** [Makefile:794: hermesc] Error 2

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':ReactAndroid:hermes-engine:buildHermes'.
> Process 'command '/home/amonra/Android/Sdk/cmake/3.18.1/bin/cmake'' finished with non-zero exit value 2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

    at makeError (/home/amonra/sandbox/fireChatvb/node_modules/execa/index.js:174:9)
    at /home/amonra/sandbox/fireChatvb/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/home/amonra/sandbox/fireChatvb/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/home/amonra/sandbox/fireChatvb/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.

```
The solution was simple yet hard to find for me 
```
sudo apt-get install libicu-dev
```
Nowhere in the docs did I ever see this instruction or package mentioned because now Hermes is self contained in the React Native. The solution is trivial, finding it is not (unless of course you are a regular user of cmake or the mentioned icu libraries).

All this would of been avoided if I had the proper setup. Hence I propose to add this instruction for linux users in the setup guide to prevent errors or missing libraries essential for a smooth run the first time.

**Comment by neildhar** [comment]
Thanks for flagging this, it has been discussed before and should be documented in the RN build instructions. Please feel free to open a PR on the RN website, or create an issue in the RN repo. I'll close this issue since it is a documentation gap in RN rather than Hermes, but I'll follow up internally as well.

cc @cortinico
