### ISSUE TITLE
RN app crashes after stopping the sampling profiler

### ISSUE THREAD

**Issue by vikascn** [facebook/hermes#943]
## Bug Description

  Using the debug menu on my android app i enabled sampling profiler, conducted my test, and then disabled the sampling profiler.

  On disabling the profiler, my app is crashing with below stack trace :

    --------- beginning of crash
    FATAL EXCEPTION: main
    Process: com.smplighthouselauncher, PID: 14016
    com.facebook.jni.CppException: std::bad_cast
    	at com.facebook.hermes.instrumentation.HermesSamplingProfiler.dumpSampledTraceToFile(Native Method)
    	at com.facebook.hermes.reactexecutor.HermesExecutorFactory.stopSamplingProfiler(HermesExecutorFactory.java:39)
    	at com.facebook.react.devsupport.DevSupportManagerBase.toggleJSSamplingProfiler(DevSupportManagerBase.java:675)
    	at com.facebook.react.devsupport.DevSupportManagerBase.access$1400(DevSupportManagerBase.java:70)
    	at com.facebook.react.devsupport.DevSupportManagerBase$13.onOptionSelected(DevSupportManagerBase.java:579)
    	at com.facebook.react.devsupport.DevSupportManagerBase$17.onClick(DevSupportManagerBase.java:633)
    	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1169)

Hermes version:
React Native version (if any): 0.64.0-rc.3
OS version (if any):
Platform: armeabi-v7a

**Comment by mattbfb** [comment]
Hi @vikascn, thanks for reporting this.

I'm having some trouble reproducing it locally on the current version of React Native. Using the RN example application (generated using `npx react-native init`), triggering the sampling profiler successfully saves the trace.

<img width="414" alt="Screenshot 2023-03-21 at 4 39 44 PM" src="https://user-images.githubusercontent.com/111091151/226735883-b0607030-ea0b-44f6-8d4d-9fbb064289ac.png">

Can you reproduce this issue on current versions of React Native?

**Comment by mattbfb** [comment]
This no longer appears to be crashing. If there's a way to reproduce on current versions of RN/Hermes, feel free to re-open the issue.
